In [1]:
import numpy as np

In [32]:

def Transf(file1,file2):
    f1= open(file1, "r")
    L=[]
    for line in f1 :
      #print(line.split())
      l = [int(x) for x in line.split()]
      L.append(l)
    a=[[round(i[0],5),round(i[1],5)] for i in L]
    nb_sommet=a[0][0]
    a=a[1:]

      #x adjacency matrix
    x=np.zeros((nb_sommet,nb_sommet))
    for i in a:
      x[i[0]][i[1]]=1
      x[i[1]][i[0]]=1

    x= x.astype(int)

    sup=[]
    deg=[]
    deg2=[]
    for i in range(nb_sommet):
      s=0
      for j in range (nb_sommet):
        if x[i][j]==1:
          s=s+1
      sup.append(s)

    for i in range(nb_sommet):
      d=0
      for j in range (nb_sommet):
        if x[i][j]==1:
          d=d+sup[j]
      deg.append(d)

    for i in range(nb_sommet):
      d2=0
      for j in range (nb_sommet):
        if x[i][j]==1:
          d2=d2+deg[j]
      deg2.append(d2)

    M=[]
    for i in range (nb_sommet):
      M.append([sup[i],deg[i],deg2[i]])
    X1=np.array([np.array(xi) for xi in M])
    x1 = X1 / X1.max(axis=0)


    f2= open(file2, "r")
    y1=[]
    for line in f2 :
      y1.append(int(line) )

    l=[0 for i in range(nb_sommet)]
    for i in y1 :
       l[i]=1
    Y1=np.asarray(l)

    return(x1,Y1)



In [33]:
file1="/content/bio-yeast.txt"
file2="/content/y_bio_yeast.txt"
Transf(file1,file2)

(array([[0.08928571, 0.20833333, 0.03575795],
        [0.05357143, 0.04761905, 0.00764059],
        [0.03571429, 0.04761905, 0.00947433],
        ...,
        [0.01785714, 0.01785714, 0.00122249],
        [0.01785714, 0.01190476, 0.00947433],
        [0.01785714, 0.01190476, 0.00091687]]), array([0, 0, 1, ..., 1, 0, 1]))

In [38]:
x_files=["ba100.txt","ba1000.txt","ba200.txt","citeseer.txt","bio_SC.txt","bio_yeast.txt","cora.txt","dimacs.txt","dimacs15.txt","er100.txt","er1000.txt","er20.txt","er200.txt","er5000.txt","grid1.txt","grid10.txt","grid50.txt","grid55.txt","grid70.txt","path.txt"]


In [39]:
d=0
for file1 in x_files :
  x1,y1=Transf(file1,"y_"+file1)
  if (d==0):
    x=x1
    y=y1
  else:
    x=np.concatenate((x,x1))
    y=np.concatenate((y,y1))

  d=d+1

In [40]:
x

array([[0.11111111, 0.21843687, 0.16595247],
       [0.26666667, 0.40480962, 0.33229451],
       [0.31111111, 0.46092184, 0.38072978],
       ...,
       [1.        , 1.        , 0.875     ],
       [1.        , 0.75      , 0.75      ],
       [0.5       , 0.5       , 0.375     ]])

In [41]:
y

array([1, 0, 0, ..., 0, 1, 0])

In [42]:
x.shape

(26917, 3)

In [43]:
y.shape

(26917,)

In [44]:
from sklearn.utils import shuffle
X, y = shuffle(x, y)


In [45]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [50]:
X=np.savetxt("/content/drive/My Drive/my_X.txt",X, delimiter=',')
y=np.savetxt("/content/drive/My Drive/my_y.txt",y)
